### ISSUE TITLE
real generics

### ISSUE THREAD

**Issue by anlhord** [go-goast/goast#11]
what's the advantage of this project compared to:

1. real generics e.g 1-parametric or n-parametric polymorphism for functions
2. fake generics implementing by breaking the silly go type system
https://github.com/gomacro/top
for example your Where function, the Top package allows user to retrieve 1
item from arbitrary type slice.

?

**Comment by jamesgarfield** [comment]
1) This is a user-space solution that approaches the problems that "real generics"* also solve. "Real generics" are a language level implementation that require a great deal more research and end up effecting the entire language. This project offers opt-in meta-programming facilities that solve the same problems, with a much lower impact. The Go authors strongly imply that `go:generate` should be explored as an option for solving this class of issues (see https://docs.google.com/document/d/1V03LUfjSADDooDMhe-_K59EgpTEm3V8uvQRuNMAEnjg/edit).

2. Obviously the answer is type-safety. goast allows you to write and maintain simple generic code that expresses intent in one place, and use it over many types in a type-safe manner. It seems this should be obvious given your question includes "breaking the type system", but perhaps you are more interested in trolling than exploring alternative approaches. 

*Please define real generics, I've seen a wide variety of implementations across various languages, and it's not clear to me that there is a single, canonical meaning.

**Comment by anlhord** [comment]
1. "Should be explored" but they nowhere promised a piece of such solution software will be re promoted as a best practice or encouraged by them. As such, your software will too be no more than a third party community project.
2. ok type safety, I agree.

trolling? we made a huge document of summary of generics discussions, I have a huge proposal put under strict review, we had a playground, preview 1 implementation for gccgo etc.

by generics I mean 1 or n-parametric polymorphism for functions.

**Comment by jamesgarfield** [comment]
1. That's fine, I don't need my project to be promoted or elevated by the core team. You say third party community project like it's some sort of negative epithet. I wrote it as a practical way to solve my problems within the ecosystem given to me by Go. If others find it useful and can use it, that's great. If it's usefulness gets replaced by language level solutions, I have no problem with that.

If you were not trolling, sorry for assuming so. Between the title topic (clearly not the approach `goast` is taking) and your tone (Go's silly type system), you must understand it was an easy mistake to make. If your summary document of generics discussions is open, I would love to see it (it is the same one Egon Elbre worked on?). Is your playground still up? That would also be great to check out.

I feel the generics topic has several possible avenues that can be explored. I like n-parametric polymorphism for functions, but I also believe that the C++ style template/macro expansion style approach to generics (http://research.swtch.com/generic) is a viable one. `goast gives you n-parametric , type-safe templates with none of the cryptic error messages you end up needing to deal with in C++.

**Comment by anlhord** [comment]
Ok thanks a lot, this clarifies it.
